name=uds-tool
version=0.2.1
author=Eszes Balazs <c4deszes@gmail.com>
maintainer=Eszes Balazs <c4deszes@gmail.com>
sentence=Diagnostic extension for LINE devices
category=Communication
architectures=*
