# Service call
UDS_SERVICE_CALL_REQUEST_ID = 0x0B00
UDS_SERVICE_POLL_REQUEST_ID = 0x0B10
UDS_SERVICE_RETURN_REQUEST_ID = 0x0B20

UDS_SERVICE_CALL_BAD_REQUEST = 0x0F

# Get diagnostic callout
UDS_PROPERTY_GET_CALL_REQUEST_ID = 0x0B80
UDS_PROPERTY_GET_RETURN_REQUEST_ID = 0x0B90

UDS_PROPERTY_GET_RETURN_NO_REQUEST = 0x00
UDS_PROPERTY_GET_RETURN_NOT_READY = 0x01
UDS_PROPERTY_GET_RETURN_NO_SUCH_PROPERTY = 0x02
UDS_PROPERTY_GET_RETURN_READ_FAILURE = 0x03
UDS_PROPERTY_GET_RETURN_BAD_REQUEST = 0x0F

UDS_PROPERTY_GET_RETURN_PREPARED = 0xFF

# Set diagnostic callout
UDS_PROPERTY_SET_CALL_REQUEST_ID = 0x0BA0
UDS_PROPERTY_SET_RETURN_REQUEST_ID = 0x0BB0

UDS_PROPERTY_SET_RETURN_NO_REQUEST = 0x00
UDS_PROPERTY_SET_RETURN_SUCCESS = 0x01
UDS_PROPERTY_SET_RETURN_NOT_READY = 0x02
UDS_PROPERTY_SET_RETURN_NO_SUCH_PROPERTY = 0x03
UDS_PROPERTY_SET_RETURN_WRITE_FAILURE = 0x04
UDS_PROPERTY_SET_RETURN_WRITE_REJECTED = 0x05
UDS_PROPERTY_SET_RETURN_BAD_REQUEST = 0x0F

UDS_PROPERTY_STATUS_MASK = 0x8000
UDS_PROPERTY_ID_RESERVED = 0x0000
