FROM mcr.microsoft.com/devcontainers/cpp:2-ubuntu-24.04

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    gcc \
    g++ \
    cmake \
    ninja-build \
    git \
    doxygen \
    graphviz \
    plantuml
