#if !defined(UDS_DIAG_H_)
#define UDS_DIAG_H_

/* Service call */
#define UDS_SERVICE_CALL_REQUEST_ID 0x0B00
#define UDS_SERVICE_RETURN_REQUEST_ID 0x0B10

#define UDS_SERVICE_CALL_BAD_REQUEST 0x0F

/* Get diagnostic callout */
#define UDS_PROPERTY_GET_CALL_REQUEST_ID 0x0B80
#define UDS_PROPERTY_GET_RETURN_REQUEST_ID 0x0B90

#define UDS_PROPERTY_GET_RETURN_NO_REQUEST 0x00
#define UDS_PROPERTY_GET_RETURN_PREPARED 0x01
#define UDS_PROPERTY_GET_RETURN_NOT_READY 0x02
#define UDS_PROPERTY_GET_RETURN_NO_SUCH_PROPERTY 0x03
#define UDS_PROPERTY_GET_RETURN_READ_FAILURE 0x04
#define UDS_PROPERTY_GET_RETURN_BAD_REQUEST 0x0F

/* Set diagnostic callout */
#define UDS_PROPERTY_SET_CALL_REQUEST_ID 0x0BA0
#define UDS_PROPERTY_SET_RETURN_REQUEST_ID 0x0BB0

#define UDS_PROPERTY_SET_RETURN_NO_REQUEST 0x00
#define UDS_PROPERTY_SET_RETURN_SUCCESS 0x01
#define UDS_PROPERTY_SET_RETURN_NOT_READY 0x02
#define UDS_PROPERTY_SET_RETURN_NO_SUCH_PROPERTY 0x03
#define UDS_PROPERTY_SET_RETURN_WRITE_FAILURE 0x04
#define UDS_PROPERTY_SET_RETURN_WRITE_REJECTED 0x05
#define UDS_PROPERTY_SET_RETURN_BAD_REQUEST 0x0F

#define UDS_PROPERTY_STATUS_MASK 0x8000
#define UDS_PROPERTY_ID_RESERVED 0x0000

#endif // UDS_DIAG_H_
